FROM ubuntu:20.04
RUN apt-get update
RUN apt-get upgrade --assume-yes
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC && \
    apt-get install --assume-yes tzdata
RUN apt-get install --assume-yes pkg-config
RUN apt-get install --assume-yes --no-install-recommends g++
RUN apt-get install --assume-yes cmake
RUN apt-get install --assume-yes libssl1.1
RUN apt-get install --assume-yes libssl-dev
