FROM debian:buster
RUN apt-get update
RUN apt-get upgrade --assume-yes
RUN dpkg --add-architecture armhf
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC && \
    apt-get install --assume-yes tzdata
RUN apt-get install --assume-yes pkg-config
RUN apt-get install --assume-yes --no-install-recommends g++-arm-linux-gnueabihf
RUN apt-get install --assume-yes libc6-dev-armhf-cross
RUN apt-get install --assume-yes cmake
RUN apt-get install --assume-yes libssl1.1:armhf
RUN apt-get install --assume-yes libssl-dev:armhf

ENV PKG_CONFIG_LIBDIR_armv7_unknown_linux_gnueabihf=/usr/lib/arm-linux-gnueabihf/pkgconfig \
    CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc \
    CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_RUNNER="/linux-runner armv7" \
    CC_armv7_unknown_linux_gnueabihf=arm-linux-gnueabihf-gcc \
    CXX_armv7_unknown_linux_gnueabihf=arm-linux-gnueabihf-g++ \
    BINDGEN_EXTRA_CLANG_ARGS_armv7_unknown_linux_gnueabihf="--sysroot=/usr/arm-linux-gnueabihf" \
    QEMU_LD_PREFIX=/usr/arm-linux-gnueabihf
