FROM debian:buster

RUN dpkg --add-architecture arm64
RUN apt-get update
RUN apt-get upgrade --assume-yes
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC && \
    apt-get install --assume-yes tzdata
RUN apt-get install --assume-yes pkg-config
RUN apt-get install --assume-yes --no-install-recommends g++-aarch64-linux-gnu
RUN apt-get install --assume-yes libc6-dev-arm64-cross
RUN apt-get install --assume-yes cmake
RUN apt-get install --assume-yes libssl1.1:arm64
RUN apt-get install --assume-yes libssl-dev:arm64
RUN apt-get install --assume-yes libsasl2-2:arm64
RUN apt-get install --assume-yes zlib1g-dev:arm64

COPY linux-runner /
COPY base-runner.sh /

COPY qemu.sh /
RUN /qemu.sh aarch64 softmmu

ENV CROSS_SYSROOT=/usr/aarch64-linux-gnu
ENV CROSS_TARGET_RUNNER="/linux-runner aarch64"
ENV PKG_CONFIG_PATH_aarch64_unknown_linux_gnu=/usr/lib/aarch64-linux-gnu/pkgconfig \
    PKG_CONFIG_LIBDIR_AARCH64_UNKNOWN_LINUX_GNU=/usr/lib/aarch64-linux-gnu/pkgconfig \
    PKG_CONFIG_SYSROOT_DIR_AARCH64_UNKNOWN_LINUX_GNU=/usr/lib/aarch64-linux-gnu \
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc \
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUNNER="$CROSS_TARGET_RUNNER" \
    CC_AARCH64_UNKNOWN_LINUX_GNU=aarch64-linux-gnu-gcc \
    CXX_AARCH64_UNKNOWN_LINUX_GNU=aarch64-linux-gnu-g++\
    BINDGEN_EXTRA_CLANG_ARGS_AARCH64_UNKNOWN_LINUX_GNU="--sysroot=/usr/aarch64-linux-gnu" \
    QEMU_LD_PREFIX=/usr/aarch64-linux-gnu \
    RUST_TEST_THREADS=1 \
    AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR=/usr/lib/aarch64-linux-gnu
