FROM --platform=linux/amd64 debian:buster

RUN dpkg --add-architecture armhf
RUN apt-get update
RUN apt-get upgrade --assume-yes
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC && \
    apt-get install --assume-yes tzdata
RUN apt-get install --assume-yes pkg-config
RUN apt-get install --assume-yes --no-install-recommends g++-arm-linux-gnueabihf
RUN apt-get install --assume-yes libc6-dev-armhf-cross
RUN apt-get install --assume-yes cmake
RUN apt-get install --assume-yes libssl1.1:armhf
RUN apt-get install --assume-yes libssl-dev:armhf
RUN apt-get install --assume-yes zlib1g-dev:armhf


COPY linux-runner /
COPY base-runner.sh /

COPY qemu.sh /
RUN /qemu.sh arm softmmu

ENV CROSS_SYSROOT=/usr/aarm-linux-gnueabihf
ENV CROSS_TARGET_RUNNER="/linux-runner armv7hf"
ENV PKG_CONFIG_PATH_armv7_unknown_linux_gnueabihf=/usr/lib/arm-linux-gnueabihf/pkgconfig \
    PKG_CONFIG_LIBDIR_ARMV7_UNKNOWN_LINUX_GNUEABIHF=/usr/lib/arm-linux-gnueabihf/pkgconfig \
    PKG_CONFIG_SYSROOT_DIR_armv7_unknown_linux_gnueabihf=/usr/lib/arm-linux-gnueabihf \
    CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc \
    CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_RUNNER="$CROSS_TARGET_RUNNER" \
    CC_ARMV7_UNKNOWN_LINUX_GNUEABIHF=arm-linux-gnueabihf-gcc \
    CXX_ARMV7_UNKNOWN_LINUX_GNUEABIHF=arm-linux-gnueabihf-g++ \
    BINDGEN_EXTRA_CLANG_ARGS_ARMV7_UNKNOWN_LINUX_GNUEABIHF="--sysroot=/usr/arm-linux-gnueabihf" \
    QEMU_LD_PREFIX=/usr/arm-linux-gnueabihf \
    RUST_TEST_THREADS=1 \
    ARMV7_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_LIB_DIR=/usr/lib/arm-linux-gnueabihf
