FROM debian:buster
RUN apt-get update
RUN apt-get upgrade --assume-yes
RUN dpkg --add-architecture arm64
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC && \
    apt-get install --assume-yes tzdata
RUN apt-get install --assume-yes pkg-config
RUN apt-get install --assume-yes --no-install-recommends g++-aarch64-linux-gnu
RUN apt-get install --assume-yes libc6-dev-arm64-cross
RUN apt-get install --assume-yes cmake
RUN apt-get install --assume-yes libssl1.1:arm64
RUN apt-get install --assume-yes libssl-dev:arm64

ENV PKG_CONFIG_LIBDIR_aarch64_unknown_linux_gnu=/usr/lib/aarch64-linux-gnu/pkgconfig \
    PKG_CONFIG_SYSROOT_DIR_aarch64_unknown_linux_gnu=/usr/lib/aarch64-linux-gnu \
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc \
    CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc \
    CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++\
    BINDGEN_EXTRA_CLANG_ARGS_aarch64_unknown_linux_gnu="--sysroot=/usr/aarch64-linux-gnu" \
    QEMU_LD_PREFIX=/usr/aarch64-linux-gnu \
    AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR=/usr/lib/aarch64-linux-gnu
