name: Docker Image CI - Feature Branch

on:
  push:
    branches-ignore:
      - 'main'
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Get Branch name
      id: vars
      run: echo ::set-output name=branch_name::${GITHUB_REF#refs/*/*/}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64,arm

    - name: Build armv7 container
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile.armv7-unknown-linux-gnubinhf
        platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
        tags: alecbrown/cross-openssl:armv7-unknown-linux-gnueabihf

    - name: Build x86_64 container
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile.x86_64-unknown-linux-gnu
        platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
        tags: alecbrown/cross-openssl:x86_64-unknown-linux-gnu
