name: Docker Image CI - Feature Branch

on:
  push:
    branches-ignore:
      - 'main'
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:

  build:
    name: "Feature CI Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Get Branch name
      id: vars
      run: echo ::set-output name=branch_name::${GITHUB_REF#refs/*/*/}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64,arm

    - name: Build container
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile.${{ matrix.TARGET }}
        platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
        tags: alecbrown/cross-openssl:${{ matrix.TARGET }}
