name: Docker Image CI

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PWD }}

    - name: Build and push armv7 container
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile.armv7-unknown-linux-gnubinhf
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: alecbrown/cross-openssl:armv7-unknown-linux-gnueabihf

    - name: Build and push x86_64 container
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile.x86_64-unknown-linux-gnu
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: alecbrown/cross-openssl:x86_64-unknown-linux-gnu
