name: Docker Image CI - Feature Branch

on:
  push:
    branches:
      - 'feature/*'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - 'feature/*'
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Branch name
      id: vars
      run: echo ::set-output name=branch_name::${GITHUB_REF#refs/*/*/}

    - name: Build and tag the docker image
      run: |
           DATETAG=$(date +%s)
           docker build . --file Dockerfile.x86_64-unknown-linux-gnu --tag alecbrown/cross-openssl:x86_64-unknown-linux-gnu-$DATETAG-${{ steps.vars.outputs.branch_name }}
           docker build . --file Dockerfile.armv7-unknown-linux-gnubinhf --tag alecbrown/cross-openssl:armv7-unknown-linux-gnueabihf-$DATETAG-${{ steps.vars.outputs.branch_name }}
