name: Docker Image CI

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:

  build:
    name: "CI Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TARGET:
          - x86_64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64,arm

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PWD }}

    - name: Build and push container
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile.${{ matrix.TARGET }}
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: alecbrown/cross-openssl:${{ matrix.TARGET }}
